[tool.poetry]
name = "railslide-blog"
version = "0.1.0"
description = "My personal blog"
authors = ["Giulia Vergottini"]

[tool.poetry.dependencies]
python = "^3.10"
pelican = "^4.7.1"
ghp-import = "^2.0.2"
Markdown = "^3.3.6"

[tool.poetry.dev-dependencies]
black = "^21.12b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
