[project]
name = "railslide-blog"
version = "0.1.0"
description = "My personal blog"
authors = ["Giulia Vergottini"]

dependencies = [
  "pelican[markdown]",
  "ghp-import",
]

[project.optional-dependencies]
dev = [
  "pip-tools"
]
